# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CameraSpec.ui'
#
# Created: Tue Feb 17 13:02:33 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CameraSpecDialog(object):
    def setupUi(self, CameraSpecDialog):
        CameraSpecDialog.setObjectName(_fromUtf8("CameraSpecDialog"))
        CameraSpecDialog.resize(504, 382)
        self.verticalLayout = QtGui.QVBoxLayout(CameraSpecDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.radioButton_2 = QtGui.QRadioButton(CameraSpecDialog)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.buttonGroup = QtGui.QButtonGroup(CameraSpecDialog)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.radioButton_2)
        self.verticalLayout.addWidget(self.radioButton_2)
        self.splitter_2 = QtGui.QSplitter(CameraSpecDialog)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.FocalLenghtBox = QtGui.QDoubleSpinBox(self.splitter_2)
        self.FocalLenghtBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.FocalLenghtBox.setObjectName(_fromUtf8("FocalLenghtBox"))
        self.label = QtGui.QLabel(self.splitter_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.splitter_2)
        self.splitter_3 = QtGui.QSplitter(CameraSpecDialog)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.PixelSizeBox = QtGui.QDoubleSpinBox(self.splitter_3)
        self.PixelSizeBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.PixelSizeBox.setObjectName(_fromUtf8("PixelSizeBox"))
        self.label_2 = QtGui.QLabel(self.splitter_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.splitter_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.PixelHor = QtGui.QSpinBox(CameraSpecDialog)
        self.PixelHor.setMaximumSize(QtCore.QSize(16777215, 30))
        self.PixelHor.setMaximum(10000)
        self.PixelHor.setObjectName(_fromUtf8("PixelHor"))
        self.horizontalLayout.addWidget(self.PixelHor)
        self.label_4 = QtGui.QLabel(CameraSpecDialog)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.PixelVert = QtGui.QSpinBox(CameraSpecDialog)
        self.PixelVert.setMaximumSize(QtCore.QSize(16777215, 30))
        self.PixelVert.setMaximum(10000)
        self.PixelVert.setObjectName(_fromUtf8("PixelVert"))
        self.horizontalLayout.addWidget(self.PixelVert)
        self.label_3 = QtGui.QLabel(CameraSpecDialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter = QtGui.QSplitter(CameraSpecDialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.DemComboBox = QtGui.QComboBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DemComboBox.sizePolicy().hasHeightForWidth())
        self.DemComboBox.setSizePolicy(sizePolicy)
        self.DemComboBox.setMaximumSize(QtCore.QSize(16777215, 50))
        self.DemComboBox.setObjectName(_fromUtf8("DemComboBox"))
        self.label_5 = QtGui.QLabel(self.splitter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.splitter)
        self.radioButton = QtGui.QRadioButton(CameraSpecDialog)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.buttonGroup.addButton(self.radioButton)
        self.verticalLayout.addWidget(self.radioButton)
        self.splitter_4 = QtGui.QSplitter(CameraSpecDialog)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.HFOVbox = QtGui.QDoubleSpinBox(self.splitter_4)
        self.HFOVbox.setEnabled(True)
        self.HFOVbox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.HFOVbox.setMaximum(360.0)
        self.HFOVbox.setObjectName(_fromUtf8("HFOVbox"))
        self.label_6 = QtGui.QLabel(self.splitter_4)
        self.label_6.setEnabled(True)
        self.label_6.setInputMethodHints(QtCore.Qt.ImhNone)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.splitter_4)
        self.splitter_5 = QtGui.QSplitter(CameraSpecDialog)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName(_fromUtf8("splitter_5"))
        self.VFOVbox = QtGui.QDoubleSpinBox(self.splitter_5)
        self.VFOVbox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.VFOVbox.setMaximum(360.0)
        self.VFOVbox.setObjectName(_fromUtf8("VFOVbox"))
        self.label_7 = QtGui.QLabel(self.splitter_5)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.splitter_5)
        self.splitter_6 = QtGui.QSplitter(CameraSpecDialog)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName(_fromUtf8("splitter_6"))
        self.verticalLayout.addWidget(self.splitter_6)
        self.buttonBox = QtGui.QDialogButtonBox(CameraSpecDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(CameraSpecDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), CameraSpecDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), CameraSpecDialog.reject)
        QtCore.QObject.connect(self.FocalLenghtBox, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.FocalLenghtBox.setValue)
        QtCore.QObject.connect(self.PixelSizeBox, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.PixelSizeBox.setValue)
        QtCore.QObject.connect(self.PixelHor, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.PixelHor.setValue)
        QtCore.QObject.connect(self.PixelVert, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.PixelVert.setValue)
        QtCore.QObject.connect(self.DemComboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.DemComboBox.setCurrentIndex)
        QtCore.QObject.connect(self.radioButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.FocalLenghtBox.show)
        QtCore.QObject.connect(self.radioButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.PixelSizeBox.show)
        QtCore.QObject.connect(self.radioButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.HFOVbox.hide)
        QtCore.QObject.connect(self.radioButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.VFOVbox.hide)
        QtCore.QObject.connect(self.radioButton, QtCore.SIGNAL(_fromUtf8("clicked()")), CameraSpecDialog.show)
        QtCore.QObject.connect(self.radioButton, QtCore.SIGNAL(_fromUtf8("clicked()")), CameraSpecDialog.show)
        QtCore.QObject.connect(self.radioButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.VFOVbox.show)
        QtCore.QObject.connect(self.radioButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.PixelSizeBox.hide)
        QtCore.QObject.connect(self.radioButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.FocalLenghtBox.hide)
        QtCore.QObject.connect(self.radioButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.label_6.show)
        QtCore.QObject.connect(self.radioButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.label_7.show)
        QtCore.QObject.connect(self.radioButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.label_2.hide)
        QtCore.QObject.connect(self.radioButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.label.hide)
        QtCore.QObject.connect(self.radioButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.label.show)
        QtCore.QObject.connect(self.radioButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.label_2.hide)
        QtCore.QObject.connect(self.radioButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.label_6.hide)
        QtCore.QObject.connect(self.radioButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.label_7.hide)
        QtCore.QObject.connect(self.radioButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.label_2.show)
        QtCore.QObject.connect(self.radioButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.HFOVbox.show)
        self.HFOVbox.hide()
        self.VFOVbox.hide()
        self.label_6.hide()
        self.label_7.hide()
        QtCore.QMetaObject.connectSlotsByName(CameraSpecDialog)

    def retranslateUi(self, CameraSpecDialog):
        CameraSpecDialog.setWindowTitle(_translate("CameraSpecDialog", "Set camera specifics and DEM", None))
        self.radioButton_2.setText(_translate("CameraSpecDialog", "Use Focal lenght and Pixel size to find Footprints", None))
        self.label.setText(_translate("CameraSpecDialog", "Focal lenght (mm)", None))
        self.label_2.setText(_translate("CameraSpecDialog", "<html><head/><body><p>Pixel size (µm)</p></body></html>", None))
        self.label_4.setText(_translate("CameraSpecDialog", "X", None))
        self.label_3.setText(_translate("CameraSpecDialog", "Resolution in pixel (Hor. x Vert.)", None))
        self.label_5.setText(_translate("CameraSpecDialog", "Dem Layer", None))
        self.radioButton.setText(_translate("CameraSpecDialog", "Use FOV\'s parameter to Find Footprints", None))
        self.label_6.setText(_translate("CameraSpecDialog", "Horizontal FOV (in degrees)", None))
        self.label_7.setText(_translate("CameraSpecDialog", "Vertical FOV (in degrees)", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    CameraSpecDialog = QtGui.QDialog()
    ui = Ui_CameraSpecDialog()
    ui.setupUi(CameraSpecDialog)
    CameraSpecDialog.show()
    sys.exit(app.exec_())

