# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OptionsDialog.ui'
#
# Created: Thu Dec  8 20:42:41 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_OptionDialog(object):
    def setupUi(self, OptionDialog):
        OptionDialog.setObjectName(_fromUtf8("OptionDialog"))
        OptionDialog.resize(813, 509)
        self.verticalLayout = QtGui.QVBoxLayout(OptionDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label = QtGui.QLabel(OptionDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setFrameShadow(QtGui.QFrame.Plain)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.FootprintsRadioButton = QtGui.QRadioButton(OptionDialog)
        self.FootprintsRadioButton.setObjectName(_fromUtf8("FootprintsRadioButton"))
        self.horizontalLayout_2.addWidget(self.FootprintsRadioButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.groupBox_2 = QtGui.QGroupBox(OptionDialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.PitchDoubleSpinBox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.PitchDoubleSpinBox.setEnabled(True)
        self.PitchDoubleSpinBox.setMinimum(-180.0)
        self.PitchDoubleSpinBox.setMaximum(180.0)
        self.PitchDoubleSpinBox.setProperty("value", -90.0)
        self.PitchDoubleSpinBox.setObjectName(_fromUtf8("PitchDoubleSpinBox"))
        self.horizontalLayout_8.addWidget(self.PitchDoubleSpinBox)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setEnabled(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_8.addWidget(self.label_10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.RollDoubleSpinBox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.RollDoubleSpinBox.setEnabled(True)
        self.RollDoubleSpinBox.setMinimum(-180.0)
        self.RollDoubleSpinBox.setMaximum(180.0)
        self.RollDoubleSpinBox.setObjectName(_fromUtf8("RollDoubleSpinBox"))
        self.horizontalLayout_7.addWidget(self.RollDoubleSpinBox)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setEnabled(True)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_7.addWidget(self.label_11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.FootprintSpinBox = QtGui.QSpinBox(self.groupBox_2)
        self.FootprintSpinBox.setEnabled(True)
        self.FootprintSpinBox.setMaximum(10000)
        self.FootprintSpinBox.setObjectName(_fromUtf8("FootprintSpinBox"))
        self.horizontalLayout.addWidget(self.FootprintSpinBox)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setEnabled(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.line_3 = QtGui.QFrame(OptionDialog)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.groupBox = QtGui.QGroupBox(OptionDialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.LoadExistentLayerradioButton = QtGui.QRadioButton(self.groupBox)
        self.LoadExistentLayerradioButton.setObjectName(_fromUtf8("LoadExistentLayerradioButton"))
        self.gridLayout.addWidget(self.LoadExistentLayerradioButton, 0, 1, 1, 1)
        self.LoadProfileLayerradioButton = QtGui.QRadioButton(self.groupBox)
        self.LoadProfileLayerradioButton.setChecked(False)
        self.LoadProfileLayerradioButton.setObjectName(_fromUtf8("LoadProfileLayerradioButton"))
        self.gridLayout.addWidget(self.LoadProfileLayerradioButton, 1, 0, 1, 2)
        self.CreateNewLayerradioButton = QtGui.QRadioButton(self.groupBox)
        self.CreateNewLayerradioButton.setChecked(True)
        self.CreateNewLayerradioButton.setObjectName(_fromUtf8("CreateNewLayerradioButton"))
        self.gridLayout.addWidget(self.CreateNewLayerradioButton, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.line_2 = QtGui.QFrame(OptionDialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.groupBox1 = QtGui.QGroupBox(OptionDialog)
        self.groupBox1.setObjectName(_fromUtf8("groupBox1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.INGVradioButton = QtGui.QRadioButton(self.groupBox1)
        self.INGVradioButton.setChecked(False)
        self.INGVradioButton.setObjectName(_fromUtf8("INGVradioButton"))
        self.gridLayout_2.addWidget(self.INGVradioButton, 0, 1, 1, 1)
        self.CustomProfileradioButton = QtGui.QRadioButton(self.groupBox1)
        self.CustomProfileradioButton.setChecked(True)
        self.CustomProfileradioButton.setObjectName(_fromUtf8("CustomProfileradioButton"))
        self.gridLayout_2.addWidget(self.CustomProfileradioButton, 0, 0, 1, 1)
        self.ThermographicradioButton = QtGui.QRadioButton(self.groupBox1)
        self.ThermographicradioButton.setObjectName(_fromUtf8("ThermographicradioButton"))
        self.gridLayout_2.addWidget(self.ThermographicradioButton, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox1)
        self.line = QtGui.QFrame(OptionDialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(OptionDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.EleOffsetSpinBox = QtGui.QDoubleSpinBox(OptionDialog)
        self.EleOffsetSpinBox.setMinimum(-1000000000.0)
        self.EleOffsetSpinBox.setMaximum(1000000000.0)
        self.EleOffsetSpinBox.setObjectName(_fromUtf8("EleOffsetSpinBox"))
        self.horizontalLayout_3.addWidget(self.EleOffsetSpinBox)
        self.label_6 = QtGui.QLabel(OptionDialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.buttonBox = QtGui.QDialogButtonBox(OptionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(OptionDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), OptionDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), OptionDialog.reject)
        QtCore.QObject.connect(self.FootprintsRadioButton, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.FootprintSpinBox.setEnabled)
        QtCore.QObject.connect(self.FootprintsRadioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.groupBox_2.setVisible)
        QtCore.QMetaObject.connectSlotsByName(OptionDialog)
        OptionDialog.setTabOrder(self.FootprintsRadioButton, self.CreateNewLayerradioButton)
        OptionDialog.setTabOrder(self.CreateNewLayerradioButton, self.LoadExistentLayerradioButton)
        OptionDialog.setTabOrder(self.LoadExistentLayerradioButton, self.LoadProfileLayerradioButton)
        OptionDialog.setTabOrder(self.LoadProfileLayerradioButton, self.CustomProfileradioButton)
        OptionDialog.setTabOrder(self.CustomProfileradioButton, self.INGVradioButton)
        OptionDialog.setTabOrder(self.INGVradioButton, self.buttonBox)
        
        self.ThermographicradioButton.hide()
        self.groupBox_2.hide()
        
    def retranslateUi(self, OptionDialog):
        OptionDialog.setWindowTitle(_translate("OptionDialog", "Options", None))
        self.label.setText(_translate("OptionDialog", "Use this option if you have a raster DEM, elevation and euler\'s angles in the gpx file.", None))
        self.FootprintsRadioButton.setText(_translate("OptionDialog", "Enable \"Foootprints\" and \"coordinate from screen\" options.", None))
        self.groupBox_2.setTitle(_translate("OptionDialog", "Set fixed pitch and roll angles (heading is retrieved from compass) and set FootPrint frequency", None))
        self.label_10.setText(_translate("OptionDialog", "Pitch", None))
        self.label_11.setText(_translate("OptionDialog", "Roll", None))
        self.label_4.setText(_translate("OptionDialog", "Set Footprints frequency in sec. (leave 0 for no footprints)", None))
        self.groupBox.setTitle(_translate("OptionDialog", "Choose point layer:", None))
        self.LoadExistentLayerradioButton.setText(_translate("OptionDialog", "Load an existent point layer", None))
        self.LoadProfileLayerradioButton.setText(_translate("OptionDialog", "Load an existent point layer associated to specific database profile", None))
        self.CreateNewLayerradioButton.setText(_translate("OptionDialog", "Create new point layer", None))
        self.groupBox1.setTitle(_translate("OptionDialog", "Database profiles:                       ", None))
        self.INGVradioButton.setText(_translate("OptionDialog", "INGV post-sismic surveys", None))
        self.CustomProfileradioButton.setText(_translate("OptionDialog", "Custom profile (make your own)", None))
        self.ThermographicradioButton.setText(_translate("OptionDialog", "Thermographic survey", None))
        self.label_5.setText(_translate("OptionDialog", "Set elevation offset: ", None))
        self.label_6.setText(_translate("OptionDialog", "mt.", None))

